// export const weekdays = ['月', '火', '水', '木', '金'];

export const weekdays = ['日', '月', '火', '水', '木', '金', '土'];

export const durationOptions = [30, 60, 90, 120];

export const employeeEmails = [
  { name: '池上 響子', email: 'k.ikegami@intelligentforce.co.jp' },
  { name: '石井 敬久', email: 't.ishii@intelligentforce.co.jp' },
  { name: '江口 弘起', email: 'h.eguchi@intelligentforce.co.jp' },
  { name: '大濱 裕太', email: 'y.ohama@intelligentforce.co.jp' },
  { name: '岡田 知也', email: 't.okada@intelligentforce.co.jp' },
  { name: '垣本 尚樹', email: 'n.kakimoto@intelligentforce.co.jp' },
  { name: '梶岡 洋平', email: 'y.kajioka@intelligentforce.co.jp' },
  { name: '甲斐 聖史', email: 'm.kai@intelligentforce.co.jp' },
  { name: '川崎 慎太郎', email: 's.kawasaki@intelligentforce.co.jp' },
  { name: '川村 真穂', email: 'm.kawamura@intelligentforce.co.jp' },
  { name: '金藤 晃大', email: 'k.kinto@intelligentforce.co.jp' },
  { name: '木下 惇', email: 'a.kinoshita@intelligentforce.co.jp' },
  { name: '木下 俊樹', email: 'kinoshita@intelligentforce.co.jp' },
  { name: '國府田 奏', email: 'k.kouda@intelligentforce.co.jp' },
  { name: '熊岡 真紀', email: 'm.kumaoka@intelligentforce.co.jp' },
  { name: '近澤 泰平', email: 't.chikazawa@intelligentforce.co.jp' },
  { name: '小関 慶二', email: 'k.ozeki@intelligentforce.co.jp' },
  { name: '白木 晴也', email: 'h.shiraki@intelligentforce.co.jp' },
  { name: '杉田 龍惟', email: 'r.sugita@intelligentforce.co.jp' },
  { name: '鈴木 泰介', email: 'suzuki@intelligentforce.co.jp' },
  { name: '戸谷 元彦', email: 'm.totani@intelligentforce.co.jp' },
  { name: '野津 今日子', email: 'k.notsu@intelligentforce.co.jp' },
  { name: '橋口 翔太', email: 's.hashiguchi@intelligentforce.co.jp' },
  { name: '橋爪 隼平', email: 's.hashizume@intelligentforce.co.jp' },
  { name: '橋本 瑞季', email: 'm.hashimoto@intelligentforce.co.jp' },
  { name: '埴岡 瞬', email: 's.hanioka@intelligentforce.co.jp' },
  { name: '深田 翔', email: 's.fukada@intelligentforce.co.jp' },
  { name: '福田 圭祐', email: 'k.fukuda@intelligentforce.co.jp' },
  { name: '福本 紘大', email: 'fukumoto@intelligentforce.co.jp' },
  { name: '細川 信之', email: 'n.hosokawa@intelligentforce.co.jp' },
  { name: '堀川 菜々', email: 'n.horikawa@intelligentforce.co.jp' },
  { name: '前田 まあ', email: 'm.maeda@intelligentforce.co.jp' },
  { name: '松井 悠', email: 'y.matsui@intelligentforce.co.jp' },
  { name: '宮田 崇生', email: 't.miyata@intelligentforce.co.jp' },
  { name: '棟田 修平', email: 's.muneta@intelligentforce.co.jp' },
  { name: '棟田 純平', email: 'j.muneta@intelligentforce.co.jp' },
  { name: '山地 茂', email: 's.yamaji@intelligentforce.co.jp' },
  { name: '山根 穂高', email: 'h.yamane@intelligentforce.co.jp' },
  { name: '山本 友亮', email: 't.yamamoto@intelligentforce.co.jp' },
  { name: '行廣 侑真', email: 'yukihiro@intelligentforce.co.jp' },
  { name: '和田 英将', email: 'h.wada@intelligentforce.co.jp' },
  { name: '渡辺 大生', email: 'd.watanabe@intelligentforce.co.jp' }
];
